apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: latency-lab

resources:
  - namespace.yaml
  - gateway.yaml
  - auth.yaml
  - risk.yaml
  - marketdata.yaml
  - execution.yaml
  - redis.yaml
  - jaeger.yaml
  - rqdelay.yaml

commonLabels:
  project: latency-attribution
